function T = resumoTable(d)
[d,~] = energia.prepararDados(d);
T = table({'Tensao media LL';'Corrente media A';'Potencia ativa media';'FP medio';'THD-I medio';'THD-V medio';'Desequilibrio max'}, ...
    [mean(d.Vll_V,'omitnan'); mean(d.Ia_A,'omitnan'); mean(d.P_kW,'omitnan'); mean(d.FP,'omitnan'); mean(d.THD_I_pct,'omitnan'); mean(d.THD_V_pct,'omitnan'); max(d.deseq_V_pct)], ...
    {'V';'A';'kW';'pu';'%';'%';'%'}, ...
    'VariableNames', {'Indicador','Valor','Unidade'});
end

